import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Application, Job, AuditEntry, CvProfile } from "@/context/AppContext";
import { CAA_LOGO_BASE64 } from "@/lib/caa-logo-base64";

const NAVY: [number, number, number] = [13, 36, 84];
const ACCENT: [number, number, number] = [201, 162, 39];

function header(doc: jsPDF, title: string, subtitle?: string) {
  // White background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, 210, 297, "F");

  // Logo (left side)
  try { doc.addImage(CAA_LOGO_BASE64, "JPEG", 10, 8, 22, 22); } catch {}

  // Organisation name (right of logo, vertically centered)
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("UGANDA CIVIL AVIATION AUTHORITY", 36, 17);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(80, 80, 80);
  doc.text("Entebbe International Airport  |  P.O. Box 5536, Kampala, Uganda", 36, 23);
  doc.text("Tel: +256 312 352 000  |  aviation@caa.co.ug  |  www.caa.co.ug", 36, 28);

  // Blue separator line (matching the letter's blue rule)
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.8);
  doc.line(10, 33, 200, 33);
  doc.setFillColor(...ACCENT);
  doc.rect(10, 33.8, 190, 0.4, "F");

  // Reference and date (like a formal letter)
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Our Ref: UCAA/HR/PORTAL", 10, 40);
  doc.text(new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" }), 200, 40, { align: "right" });

  // Document title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text(title.toUpperCase(), 10, 50);
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(0.3);
  doc.line(10, 52, Math.min(10 + doc.getTextWidth(title.toUpperCase()), 200), 52);

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(subtitle, 10, 58);
  }
}

function footer(doc: jsPDF, actor: string) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    // Footer rule
    doc.setDrawColor(...NAVY);
    doc.setLineWidth(0.5);
    doc.line(10, 283, 200, 283);
    doc.setFontSize(7.5);
    doc.setTextColor(80, 80, 80);
    doc.setFont("helvetica", "normal");
    doc.text("Uganda Civil Aviation Authority — Confidential HR Document. Not for external distribution.", 10, 287);
    doc.text(`Generated by ${actor}`, 10, 291);
    doc.text(`Page ${i} of ${pages}`, 200, 291, { align: "right" });
  }
}

export function downloadJobsReport(jobs: Job[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Vacancies Report", `${jobs.length} listings as at ${new Date().toLocaleDateString()}`);
  autoTable(doc, {
    startY: 65,
    head: [["#", "Title", "Department", "Band", "Visibility", "Closes", "Min Age", "Exp (yrs)"]],
    body: jobs.map((j) => [j.id, j.title, j.dept, j.salaryBand, j.visibility, j.closes, j.minAge, j.requiredExperience]),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-vacancies-${Date.now()}.pdf`);
}

export function downloadApplicationsReport(apps: Application[], jobs: Job[], actor: string, title = "Applications Report") {
  const doc = new jsPDF();
  const byStatus: Record<string, number> = {};
  apps.forEach((a) => (byStatus[a.status] = (byStatus[a.status] ?? 0) + 1));
  header(doc, title, `${apps.length} applications across ${new Set(apps.map((a) => a.jobId)).size} vacancies`);

  autoTable(doc, {
    startY: 65,
    head: [["Status", "Count"]],
    body: Object.entries(byStatus).map(([s, n]) => [s, n]),
    headStyles: { fillColor: NAVY, textColor: 255 },
    styles: { fontSize: 9, cellPadding: 2.5 },
    tableWidth: 80,
  });

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 8,
    head: [["#", "Candidate", "Email", "Role", "Department", "Submitted", "Status"]],
    body: apps.map((a) => {
      const job = jobs.find((j) => j.id === a.jobId);
      return [a.id, a.candidateName ?? "—", a.candidateEmail ?? "—", a.title, job?.dept ?? a.dept, a.date, a.status];
    }),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-applications-${Date.now()}.pdf`);
}

export function downloadDepartmentSummary(jobs: Job[], apps: Application[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Departmental Recruitment Summary", "Active listings and pipeline by department");
  const depts = Array.from(new Set(jobs.map((j) => j.dept)));
  const rows = depts.map((d) => {
    const dJobs = jobs.filter((j) => j.dept === d);
    const dApps = apps.filter((a) => dJobs.some((j) => j.id === a.jobId));
    return [d, dJobs.length, dApps.length, dApps.filter((a) => a.status === "Shortlisted").length, dApps.filter((a) => a.status === "Hired").length];
  });
  autoTable(doc, {
    startY: 65,
    head: [["Department", "Listings", "Applications", "Shortlisted", "Hired"]],
    body: rows,
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9, cellPadding: 3 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-dept-summary-${Date.now()}.pdf`);
}

export function downloadAuditLog(audit: AuditEntry[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Admin Audit Log", `${audit.length} most recent actions`);
  autoTable(doc, {
    startY: 65,
    head: [["Timestamp", "Actor", "Role", "Action", "Target"]],
    body: audit.map((e) => [new Date(e.at).toLocaleString(), e.actor, e.role, e.action, e.target ?? ""]),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-audit-${Date.now()}.pdf`);
}

function openPdfInTab(doc: jsPDF, fallbackName: string) {
  try {
    const url = doc.output("bloburl") as unknown as string;
    const w = window.open(url, "_blank");
    if (!w) doc.save(fallbackName);
  } catch {
    doc.save(fallbackName);
  }
}

export function downloadCandidateCv(cv: CvProfile, app: Application | undefined, actor: string, opts?: { preview?: boolean }) {
  const doc = new jsPDF();
  const name = `${cv.personal.firstName} ${cv.personal.lastName}`.trim() || app?.candidateName || "Candidate";
  header(doc, `Candidate Dossier — ${name}`, app ? `${app.title} • Submitted ${app.date} • ${app.status}` : "CV on file");

  let y = 68;
  doc.setTextColor(13, 36, 84); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
  doc.text("Personal Details", 12, y); y += 5;
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
  const p = cv.personal;
  const personal = [
    ["Full name", `${p.firstName} ${p.otherName ?? ""} ${p.lastName}`.replace(/\s+/g, " ").trim()],
    ["Date of birth", p.dob || "—"], ["Gender", p.gender || "—"],
    ["Nationality", p.nationality || "—"], ["NIN", p.nin || "—"],
    ["Phone", p.phone || "—"], ["Email", p.email || "—"],
    ["Address", p.address || "—"],
  ];
  autoTable(doc, { startY: y, body: personal, theme: "plain", styles: { fontSize: 9, cellPadding: 1.5 }, columnStyles: { 0: { fontStyle: "bold", cellWidth: 38, textColor: [90, 90, 90] } } });
  y = (doc as any).lastAutoTable.finalY + 6;

  if (cv.qualifications.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Qualifications", 12, y); y += 2;
    autoTable(doc, {
      startY: y + 2,
      head: [["Level", "Course / Award", "Institution", "Year"]],
      body: cv.qualifications.map((q) => [q.level, q.course || q.school || "—", q.institution || q.school || "—", q.year || "—"]),
      headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  if (cv.experience.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Work Experience", 12, y); y += 2;
    autoTable(doc, {
      startY: y + 2,
      head: [["Title", "Organisation", "Start", "End", "Notes"]],
      body: cv.experience.map((e) => [e.title, e.organisation, e.start, e.end, e.description]),
      headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
    });
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  if (cv.skills.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Skills", 12, y); y += 5;
    doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
    doc.text(cv.skills.join(" · "), 12, y, { maxWidth: 186 });
    y += 8;
  }

  if (cv.referees.length) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
    doc.text("Referees", 12, y); y += 2;
    autoTable(doc, {
      startY: y + 2,
      head: [["Name", "Title", "Organisation", "Phone", "Email"]],
      body: cv.referees.filter((r) => r.name).map((r) => [r.name, r.title, r.organisation, r.phone, r.email]),
      headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
    });
  }

  footer(doc, actor);
  const file = `caa-candidate-${name.replace(/\s+/g, "-").toLowerCase()}.pdf`;
  if (opts?.preview) openPdfInTab(doc, file); else doc.save(file);
}

export type StaffRecord = {
  empNo: string; firstName: string; lastName: string;
  dept: string; position: string; email: string; joined: string; status: string;
};

export function downloadInternsReport(apps: Application[], jobs: Job[], actor: string) {
  const doc = new jsPDF();
  const sorted = [...apps].filter((a) => a.cgpa !== undefined).sort((a, b) => (b.cgpa ?? 0) - (a.cgpa ?? 0));
  header(doc, "Intern Applications — CGPA Ranking", `${sorted.length} applications ranked by academic performance`);
  autoTable(doc, {
    startY: 65,
    head: [["Rank", "Candidate", "Email", "Position", "CGPA", "University", "Status", "Submitted"]],
    body: sorted.map((a, i) => {
      const job = jobs.find((j) => j.id === a.jobId);
      return [i + 1, a.candidateName ?? "—", a.candidateEmail ?? "—", job?.title ?? a.title, a.cgpa?.toFixed(1) ?? "—", a.university ?? "—", a.status, a.date];
    }),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-interns-cgpa-${Date.now()}.pdf`);
}

export function downloadStaffReport(staff: StaffRecord[], actor: string) {
  const doc = new jsPDF();
  header(doc, "Internal Staff Register", `${staff.length} verified CAA staff records`);
  autoTable(doc, {
    startY: 65,
    head: [["Emp No.", "Full Name", "Department", "Position", "Email", "Joined", "Status"]],
    body: staff.map((s) => [s.empNo, `${s.firstName} ${s.lastName}`, s.dept, s.position, s.email, s.joined, s.status]),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8, cellPadding: 2 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });
  footer(doc, actor);
  doc.save(`caa-staff-register-${Date.now()}.pdf`);
}

export function downloadShortlistedDossiers(
  apps: Application[],
  jobs: Job[],
  cvByEmail: Record<string, CvProfile>,
  actor: string,
) {
  const doc = new jsPDF();
  header(
    doc,
    "Shortlisted Candidates — Bulk Dossier",
    `${apps.length} shortlisted candidate${apps.length === 1 ? "" : "s"} across ${new Set(apps.map((a) => a.jobId)).size} vacancy(ies)`,
  );

  autoTable(doc, {
    startY: 65,
    head: [["#", "Candidate", "Email", "Role", "Department", "Submitted"]],
    body: apps.map((a, i) => {
      const j = jobs.find((x) => x.id === a.jobId);
      return [i + 1, a.candidateName ?? "—", a.candidateEmail ?? "—", a.title, j?.dept ?? a.dept, a.date];
    }),
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    alternateRowStyles: { fillColor: [245, 247, 250] },
  });

  apps.forEach((a, idx) => {
    doc.addPage();
    const name = a.candidateName || "Candidate";
    const job = jobs.find((j) => j.id === a.jobId);
    header(
      doc,
      `Dossier ${idx + 1} of ${apps.length} — ${name}`,
      `${a.title}${job ? ` • ${job.dept}` : ""} • Submitted ${a.date}`,
    );

    let y = 68;
    doc.setTextColor(13, 36, 84); doc.setFont("helvetica", "bold"); doc.setFontSize(11);
    doc.text("Application Summary", 12, y); y += 4;
    autoTable(doc, {
      startY: y,
      theme: "plain",
      body: [
        ["Application ID", String(a.id)],
        ["Candidate", name],
        ["Email", a.candidateEmail ?? "—"],
        ["Role applied", a.title],
        ["Department", job?.dept ?? a.dept],
        ["Salary band", job?.salaryBand ?? "—"],
        ["Visibility", job?.visibility ?? "—"],
        ["Submitted", a.date],
        ["Status", a.status],
        ["Profile completion", `${a.completion}%`],
      ],
      styles: { fontSize: 9, cellPadding: 1.5 },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 48, textColor: [90, 90, 90] } },
    });
    y = (doc as any).lastAutoTable.finalY + 6;

    const cv = a.candidateEmail ? cvByEmail[a.candidateEmail.toLowerCase()] : undefined;
    if (cv) {
      const p = cv.personal;
      doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
      doc.text("Personal Details", 12, y); y += 4;
      autoTable(doc, {
        startY: y, theme: "plain",
        body: [
          ["Full name", `${p.firstName} ${p.otherName ?? ""} ${p.lastName}`.replace(/\s+/g, " ").trim() || "—"],
          ["Date of birth", p.dob || "—"], ["Gender", p.gender || "—"],
          ["Nationality", p.nationality || "—"], ["NIN", p.nin || "—"],
          ["Phone", p.phone || "—"], ["Address", p.address || "—"],
        ],
        styles: { fontSize: 9, cellPadding: 1.5 },
        columnStyles: { 0: { fontStyle: "bold", cellWidth: 38, textColor: [90, 90, 90] } },
      });
      y = (doc as any).lastAutoTable.finalY + 6;

      if (cv.qualifications.length) {
        doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
        doc.text("Qualifications", 12, y);
        autoTable(doc, {
          startY: y + 2,
          head: [["Level", "Course / Award", "Institution", "Year"]],
          body: cv.qualifications.map((q) => [q.level, q.course || q.school || "—", q.institution || q.school || "—", q.year || "—"]),
          headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
        });
        y = (doc as any).lastAutoTable.finalY + 6;
      }

      if (cv.experience.length) {
        doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
        doc.text("Work Experience", 12, y);
        autoTable(doc, {
          startY: y + 2,
          head: [["Title", "Organisation", "Start", "End", "Notes"]],
          body: cv.experience.map((e) => [e.title, e.organisation, e.start, e.end, e.description]),
          headStyles: { fillColor: NAVY, textColor: 255 }, styles: { fontSize: 8.5, cellPadding: 2 },
        });
        y = (doc as any).lastAutoTable.finalY + 6;
      }

      if (cv.skills.length) {
        doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(13, 36, 84);
        doc.text("Skills", 12, y); y += 5;
        doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(40, 40, 40);
        doc.text(cv.skills.join(" · "), 12, y, { maxWidth: 186 });
      }
    } else {
      doc.setFont("helvetica", "italic"); doc.setFontSize(9); doc.setTextColor(120, 120, 120);
      doc.text("Full CV profile not available offline for this candidate. Open the candidate record in the HR Console to view the live dossier.", 12, y, { maxWidth: 186 });
    }
  });

  footer(doc, actor);
  doc.save(`caa-shortlist-dossiers-${Date.now()}.pdf`);
}